apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-techmang3-api
  namespace: {{ constants["deploy_env_status"] }}-techmang3
spec:
  replicas: 1
  selector:
    matchLabels:
      module: techmang3-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        module: techmang3-api
    spec:
      containers:
      - image: {{ constants[constants["deploy_env_status"]]["techmang3-api"]["image"] }}:{{ constants["docker_image_version"] }}
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        imagePullPolicy: Always
        name: container-api
        ports:
        - name: p-api
          containerPort: 8989
        command: ["python3", "/app/api.py"]
