apiVersion: v1
kind: Service
metadata:
  name: service-api
  namespace: {{ constants["deploy_env_status"] }}-techmang3
spec:
  ports:
    - port: 8989
      targetPort: p-api
      nodePort: {{ constants[constants["deploy_env_status"]]["techmang3-api"]["node_port"] }}
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    module: techmang3-api
