apiVersion: v1
kind: Service
metadata:
  name: service-webapp
  namespace: {{ constants["deploy_env_status"] }}-techmang3
spec:
  ports:
    - port: 80
      targetPort: p-webapp
      nodePort: {{ constants[constants["deploy_env_status"]]["techmang3-webapp"]["node_port"] }}
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    module: techmang3-webapp
